### PR TITLE
Add all contributors bot

### PR DESCRIPTION
**Pull request by JimMadge**
## Summary

- Add all contributors bot
- The table is not currently in the book
- This doesn't populate the table

## Related issues

- Contributes to #70

## Screenshots

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### CODE REVIEW

**Comment by JimMadge** [comment]
@all-contributors
please add @andrewphilipsmith for content, review, ideas, code, design
please add @mhauru for content, ideas
please add @mastoffel for content
please add @dsj976 for content
please add @LydiaFrance for content
please add @yongrenjie for content, ideas
please add @llewelld for content, ideas, bug
please add @jemrobinson for content
please add @KatrionaGoldmann for content, review
please add @fedenanni for content, ideas
please add @thobson88 for content
please add @ChristinaLast for content
please add @jack89roberts for content
please add @nbarlowATI for ideas
please add @OscartGiles for ideas
please add @martintoreilly for ideas
please add @malvikasharan for ideas

**Comment by JimMadge** [comment]
Might have hit an API limit. Have you seen that before @malvikasharan?

**Comment by jack89roberts** [comment]
I tried to do a big block of people in one go for the RDS course recently and in the end found it worked better just to use the CLI to edit `.all-contributorsrc` locally: https://allcontributors.org/docs/en/cli/installation

**Comment by JimMadge** [comment]
@jack89roberts I've been looking at the docs. I know there is a CLI. It is obviously the much easier way to do this. Didn't think to do it 🤦

**Pull request merged**
