### PR TITLE
Update Systems Set Up page

### PR DESCRIPTION
**Pull request by llewelld**
## Summary

1. Remove reference to the no-longer-used Planning Kanban.
2. Update the Slack channel suggestions.
3. Remove reference to the "tasks" standup which no longer exists.

## Related issues

N/A

## Screenshots

N/A

### CODE REVIEW

**Comment by llewelld** [comment]
I'm taking the opportunity to test out making changes. Apologies in advance if I'm not following the correct process.

**Comment by andrewphilipsmith** [comment]
Looks good to me. Feel free to merge when you're ready.

**Review by JimMadge — APPROVED** [review]
LGTM :+1:

**Comment by llewelld** [comment]
Thanks for the reviews and help!

**Pull request merged**
